data_params:
  in_dir: ./data/flower_photos

model_params:
  model_name: unet

opt_params:
  lr: 0.0007

trainer_params:
  device: 'cuda'
  batch_size: 16
  data_workers: 4
  epochs: 1000

log_params:
  log_dir: logs/Unet
  seed: 42

val_params:
  val_size: 370
  batch_size: 64
  data_workers: 4
