data_params:
  in_dir: ./data/flower_photos

model_params:
  model_name: resnet_patch
  block_dims: [3,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,3]

opt_params:
  lr: 0.0001

trainer_params:
  device: 'cuda'
  batch_size: 16
  data_workers: 4
  epochs: 1000

log_params:
  log_dir: logs/ResNet
  seed: 42

eval_params:
  